# Generated by Django 4.0.2 on 2022-02-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_book_author_book_is_best_selling_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_best_selling',
            field=models.BooleanField(default=False),
        ),
    ]
